fail_on_violations: true

scss:
  enabled: true
  config_file: .scss-lint.yml

javascript:
  enabled: true
  config_file: .jshintrc

eslint:
  enabled: true
  config_file: .eslintrc.yml

coffeescript:
  enabled: false

ruby:
  enabled: false

swift:
  enabled: false
